/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cxy_jnidemo_HelloWorld */

#ifndef _Included_com_example_cxy_jnidemo_HelloWorld
#define _Included_com_example_cxy_jnidemo_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cxy_jnidemo_HelloWorld
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cxy_jnidemo_HelloWorld_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
